### PR TITLE
Update build.yml

### PR DESCRIPTION
**Pull request by stephen-pl**
Thinking that the images should be called spade-retrieval bot

### CODE REVIEW

**Review by stephen-pl — COMMENTED** [review]
added --fix to linter

**Review by stephen-pl — COMMENTED** [review]
only look at new changes

**Review by stephen-pl — COMMENTED** [review]
back to first commit

**Comment by stephen-pl** [comment]
build and tests run fine. The issue seems to be with the linter. @jcace do you want to fix all the linter issues now or do it after things get into a stable state.

**Review by stephen-pl — COMMENTED** [review]
only looking at new issues for now

**Review by stephen-pl — COMMENTED** [review]
removing param that shouldnt be needed anymore

**Review by jcace — APPROVED** [review]
LGTM

**Pull request merged**
